services:
    app:
        build:
            context: ./docker
        tty: true
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - 8099:80
        volumes:
            - .:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d
    node:
        image: node:20-alpine
        working_dir: /home/node/app
        volumes:
            - .:/home/node/app
            - ./docker/node:/bin/node
        ports:
            - 5173:5173
        entrypoint: /bin/node/entrypoint.sh
    db:
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./db:/var/lib/postgresql/data
            - ./docker/db:/docker-entrypoint-initdb.d
networks:
    user-crud:
        driver: bridge
